@MassTransit.Api_HostAddress = http://localhost:5120

GET {{MassTransit.Api_HostAddress}}/weatherforecast/
Accept: application/json


POST {{MassTransit.Api_HostAddress}}/weatherforecast/
Content-Type: application/json

{

}


###
